 # See https://blog.daemonl.com/2016/02/yaml.html for anchor syntax


 #-----------
 # ON VITO VM
 #-----------


 # AL_BB_DH 
 # --------
 
c3s_al_bbdh_AVHRR:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALBB_DH_Global_4KM_V2/V2.0.1'
    <<: &param
        source: 'c3s'
        mode: 'walk'  
        freq: '10D'
    <<: &varbbdh
        var:
            - 'AL_DH_BB'
            - 'AL_DH_NI'
            - 'AL_DH_VI'

c3s_al_bbdh_VGT:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALBB_DH_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varbbdh
    
c3s_al_bbdh_PROBAV:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALBB_DH_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varbbdh

c3s_al_bbdh_SENTINEL3:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALBB_DH_Global_300M_V3/V3.0.1'
    <<: *param
    <<: *varbbdh

 # AL_BB_BH 
 # --------
 
c3s_al_bbbh_AVHRR:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALBB_BH_Global_4KM_V2/V2.0.1'
    <<: *param
    <<: &varbbbh
        var:
            - 'AL_BH_BB'
            - 'AL_BH_NI'
            - 'AL_BH_VI'

c3s_al_bbbh_VGT:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALBB_BH_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varbbbh
    
c3s_al_bbbh_PROBAV:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALBB_BH_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varbbbh

c3s_al_bbbh_SENTINEL3:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALBB_BH_Global_300M_V3/V3.0.1'
    <<: *param
    <<: *varbbbh

 # AL_SP_DH 
 # --------
 
c3s_al_spdh_AVHRR:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALSP_DH_Global_4KM_V2/V2.0.1'
    <<: *param
    <<: &varspdh
        var:
            - 'AL_DH_B0'
            - 'AL_DH_B2'
            - 'AL_DH_B3'
            - 'AL_DH_MIR'

c3s_al_spdh_VGT:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALSP_DH_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varspdh
    
c3s_al_spdh_PROBAV:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALSP_DH_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varspdh

c3s_al_spdh_SENTINEL3:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALSP_DH_Global_300M_V3/V3.0.1'
    <<: *param
    var:
        - 'AL_DH_Oa03'   
        - 'AL_DH_Oa04'   
        - 'AL_DH_Oa07'   
        - 'AL_DH_Oa17'   
        - 'AL_DH_Oa21'  
        - 'AL_DH_S1'     
        - 'AL_DH_S2'     
        - 'AL_DH_S5'     
        - 'AL_DH_S6'     


 # AL_SP_BH 
 # --------
 
c3s_al_spbh_AVHRR:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALSP_BH_Global_4KM_V2/V2.0.1'
    <<: *param
    <<: &varspbh
        var:
            - 'AL_BH_B0'
            - 'AL_BH_B2'
            - 'AL_BH_B3'
            - 'AL_BH_MIR'

c3s_al_spbh_VGT:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALSP_BH_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varspbh
    
c3s_al_spbh_PROBAV:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALSP_BH_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varspbh

c3s_al_spbh_SENTINEL3:
    root: '/data/c3s_pdf_live/MTDA/C3S_ALSP_BH_Global_300M_V3/V3.0.1'
    <<: *param
    var:
        - 'AL_BH_Oa03'   
        - 'AL_BH_Oa04'   
        - 'AL_BH_Oa07'   
        - 'AL_BH_Oa17'   
        - 'AL_BH_Oa21'  
        - 'AL_BH_S1'     
        - 'AL_BH_S2'     
        - 'AL_BH_S5'     
        - 'AL_BH_S6'     


 # LAI 
 # --------
 
c3s_lai_AVHRR:
    root: '/data/c3s_pdf_live/MTDA/C3S_LAI_Global_4KM_V1/V1.0.1'
    <<: *param
    <<: &varlai
        var:
            - 'LAI'

c3s_lai_VGT:
    root: '/data/c3s_pdf_live/MTDA/C3S_LAI_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varlai
    
c3s_lai_PROBAV:
    root: '/data/c3s_pdf_live/MTDA/C3S_LAI_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varlai

 # fAPAR 
 # --------
 
c3s_fapar_AVHRR:
    root: '/data/c3s_pdf_live/MTDA/C3S_FAPAR_Global_4KM_V1/V1.0.1'
    <<: *param
    <<: &varfapar
        var:
            - 'fAPAR'

c3s_fapar_VGT:
    root: '/data/c3s_pdf_live/MTDA/C3S_FAPAR_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varfapar
    
c3s_fapar_PROBAV:
    root: '/data/c3s_pdf_live/MTDA/C3S_FAPAR_Global_1KM_V2/V2.0.1'
    <<: *param
    <<: *varfapar

 #---------------------------------------------

 # Dir to store cache and output
output_path:
    extract: './output_extract'
    merge: './output_merge'
    trend: './output_trend'
    plot: './output_plot'
    merged_filename: 'merged_trends.nc'

 # Input file with reference site coordinates
 # (read only if input type = latloncsv)
ref_site_coor:
    AVHRR: './LANDVAL_v1.1.csv'
    VGT: './LANDVAL_v1.1_avhrr_topleft.csv'
    PROBAV: './LANDVAL_v1.1_avhrr_topleft.csv'
    SENTINEL3: './LANDVAL_v1.1_avhrr_topleft.csv'

